name: game2048
description: A beautiful 2048 game built with Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
